name: Add issue to project area given a specific label
on:
  issues:
    types: [ labeled ]

env:
  TYPESCRIPT_PROJECT_URL: https://github.com/users/matthewgallo/projects/1
  LABEL_TYPESCRIPT: 'TypeScript'
jobs:
  add-to-project:
    name: Add issue with typescript label to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 #v1.0.0
        with:
          labeled: ${{ env.LABEL_TYPESCRIPT }}
          project-url: ${{ env.TYPESCRIPT_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}