name: Moves labeled issues to a specific project area

on:
  issues:
    types: [ labeled ]

jobs:
  move-ts-issues:
    if: ${{ github.event.label.name == 'TypeScript' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Area'
      field_option: '🟦 Typescript'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-test-issues:
    if: ${{ github.event.label.name == 'Testing' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Area'
      field_option: '🚧 Testing'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
